name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
defaults:
  run:
    working-directory: ./
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm@9.7.0

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: |
          pnpm exec playwright install chromium --with-deps
          pnpm exec playwright install firefox --with-deps
          pnpm exec playwright install webkit --with-deps

      - name: Run tests
        run: pnpm test:coverage && pnpm test:e2e

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: unittests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
