name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm build

      - name: Install Playwright browsers
        run: |
          pnpm playwright install chromium --with-deps
          pnpm playwright install firefox --with-deps
          pnpm playwright install webkit --with-deps

      - name: Run tests and collect coverage
        run: |
          pnpm test -- --coverage
          pnpm test:e2e

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: unittests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}